name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build --refresh-dependencies

      - name: Upload jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/company-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/

      - name: Run jar on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            echo "🛑 기존 애플리케이션 종료 시도 중..."
            pkill -f 'java.*company-0.0.1-SNAPSHOT.jar' || echo "No previous process"

            echo "🚀 새 JAR 실행 중..."
      - name: Run jar on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu

            echo "🛑 기존 애플리케이션 종료 시도 중..."
            pkill -f 'java.*company-0.0.1-SNAPSHOT.jar' || echo "No previous process"

            echo "🔧 tmux 설치 확인 중..."
            command -v tmux || (sudo apt update && sudo apt install -y tmux)

            echo "🚀 새 JAR 실행 중 (tmux)..."
            tmux new-session -d -s deploy 'java -jar company-0.0.1-SNAPSHOT.jar > app.log 2>&1'

            echo "✅ 배포 완료"

          
